name: Build and Deploy to Cloud Run

on: [ workflow_dispatch ]

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: gin-gorm-run-sql
  DOCKER_BUILDKIT: 1

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      - name: Configure Docker to use the gcloud command-line tool as a credential
        run: |-
          gcloud auth configure-docker

      - name: Build
        run: |-
          docker build --target deploy --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" .

      - name: Push the Docker image to Google Container Registry
        run: |-
          docker push "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      # GCRのイメージをCloudRunにデプロイ
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
